[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[project]
name = "subvortex"
dynamic = ["version"]
description = "SubVortex Miner"
authors = [{ name = "Eclipse Vortex", email = "subvortex.bt@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.setuptools.dynamic]
version = { attr = "subvortex.miner.version.__version__" }

[project.license]
text = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = [
    "subvortex",
    "subvortex.core",
    "subvortex.miner",
    "subvortex.scripts",
]

[tool.setuptools.package-data]
"subvortex" = ["pyproject.toml"]
"subvortex.miner" = [
    "**/*.py",
    "**/deployment/**/*",
    "**/scripts/**/*",
    "**/pyproject.toml",
    "**/requirements.txt",
    "**/README.md",
    "**/env.template",
    "**/docker-compose.yml",
]
"subvortex.core" = ["**/*.py"]
"subvortex.scripts" = ["**/*.sh"]

[tool.setuptools.exclude-package-data]
"subvortex" = ["**/venv/*", "**/.venv/*"]
"subvortex.miner" = ["**/venv/*", "**/.venv/*"]
"subvortex.core" = ["**/venv/*", "**/.venv/*"]
