services:
  miner:
    build:
      context: ..
      dockerfile: ./miner/neuron/Dockerfile
    image: subvortex-miner:latest
    container_name: subvortex-miner
    restart: always
    ports:
      - "127.0.0.1:8091:8091"
    networks:
      - net
    env_file:
      - ./neuron/.env
    volumes:
      - ${HOME}/.bittensor/wallets:/root/.bittensor/wallets
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "7091" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  net:
    driver: bridge
