# Failure rewards
SUBTENSOR_FAILURE_REWARD = 0.0
METRIC_FAILURE_REWARD = 0.0
CHALLENGE_FAILURE_REWARD = -0.01

# Failure rewards
AVAILABILITY_FAILURE_REWARD = 0.0
LATENCY_FAILURE_REWARD = 0.0
DISTRIBUTION_FAILURE_REWARD = 0.0
RELIABILLITY_FAILURE_REWARD = 0.0

# Score weights
AVAILABILITY_WEIGHT = 3.0
LATENCY_WEIGHT = 1.0
RELIABILLITY_WEIGHT = 1.0
DISTRIBUTION_WEIGHT = 1.0

# Success rewards
SUPER_SAIYAN_TIER_REWARD_FACTOR = 1.0
DIAMOND_TIER_REWARD_FACTOR = 0.888
GOLD_TIER_REWARD_FACTOR = 0.777
SILVER_TIER_REWARD_FACTOR = 0.666
BRONZE_TIER_REWARD_FACTOR = 0.555

SUPER_SAIYAN_TIER_TOTAL_SUCCESSES = 10**4  # 10,000
DIAMOND_TIER_TOTAL_SUCCESSES = 10**3 * 5   # 5,000
GOLD_TIER_TOTAL_SUCCESSES = 10**3 * 2      # 2,000
SILVER_TIER_TOTAL_SUCCESSES = 10**3        # 1,000

SUPER_SAIYAN_WILSON_SCORE = 0.88
DIAMOND_WILSON_SCORE = 0.77
GOLD_WILSON_SCORE = 0.66
SILVER_WILSON_SCORE = 0.55
