# Failure rewards
AVAILABILITY_FAILURE_REWARD = 0.0
LATENCY_FAILURE_REWARD = 0.0
DISTRIBUTION_FAILURE_REWARD = 0.0
RELIABILLITY_FAILURE_REWARD = 0.0

# Score weights
AVAILABILITY_WEIGHT = 8
LATENCY_WEIGHT = 8
RELIABILLITY_WEIGHT = 3
DISTRIBUTION_WEIGHT = 1

# Reset config
RELIABILLITY_RESET = 1080 # Reset challenge statistics every 3 epochs

DEFAULT_PROCESS_TIME = 5

# UID Subnet 
TESTNET_SUBNET_UID = 92
MAIN_SUBNET_UID = 7

# Selectiom
DEFAULT_CHUNK_SIZE = 10