# Failure rewards
AVAILABILITY_FAILURE_REWARD = 0.0
LATENCY_FAILURE_REWARD = 0.0
DISTRIBUTION_FAILURE_REWARD = 0.0
RELIABILLITY_FAILURE_REWARD = 0.0

# Score weights
AVAILABILITY_WEIGHT = 3.0
LATENCY_WEIGHT = 1.0
RELIABILLITY_WEIGHT = 1.0
DISTRIBUTION_WEIGHT = 1.0

# Reset config
RELIABILLITY_RESET = 1080 # Reset challenge statistics every 3 epochs